app/app/models.py
from sqlalchemy.sql.expression import null
from app import db, login_manager
from app.globals import queueType, statusType, roleType, invalidChar
from flask_login import UserMixin
from sqlalchemy import Column, Integer, String, Enum, DateTime, Text
from sqlalchemy.orm import validates
from werkzeug.security import generate_password_hash, check_password_hash

# Checking Types
from sqlalchemy.orm.attributes import InstrumentedAttribute
import types

# User table
class BaseModel(db.Model):

    __abstract__ = True

    def to_dict(self):
        classVars = vars(type(self))  # get any "default" attrs defined at the class level
        instanceVars = vars(self)  # get any attrs defined on the instance (self)
        allVars = dict(classVars)
        allVars.update(instanceVars)
        # filter out private attributes, functions and SQL_Alchemy references
        publicVars = {key: value for key, value in allVars.items() if not (key.startswith('_') or (
            isinstance(value, types.FunctionType)) or (isinstance(value, InstrumentedAttribute)))}
        return publicVars


class User(BaseModel, UserMixin):
    __tablename__ = 'user'

    id = Column(Integer, primary_key=True)
    username = Column(String(64), index=True, unique=True, nullable=False)
    password_hash = Column(String(128), nullable=False)
    role = Column(Text, nullable=False)

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password, method='sha256')

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    @validates
    def validate_role(self, key, role):
        if role not in roleType:
            raise ValueError("Invalid roleType")
        else:
            return role

@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))


# Queue model for db

class Queue(BaseModel):

    id = Column(Integer, primary_key=True)
    studentName = Column(String(64), nullable=False)
    studentNumber = Column(Integer, nullable=False)
    unitCode = Column(String(8), nullable=False)
    enquiry = Column(Text, nullable=False)
    queue = Column(Text, nullable=False)
    status = Column(Text, nullable=False)
    enterQueueTime = Column(DateTime, nullable=False)
    changeSessionTime = Column(DateTime)
    exitSessionTime = Column(DateTime)

    def __init__(self, studentName, studentNumber, unitCode, enquiry, queue, status, enterQueueTime):
        self.studentName = studentName
        self.studentNumber = studentNumber
        self.unitCode = unitCode
        self.enquiry = enquiry
        self.queue = queue
        self.status = status
        self.enterQueueTime = enterQueueTime

    def __repr__(self):
        return f"<Queue #{self.id}{{Name: {self.studentName}, ID: {self.studentNumber}, Unit: {self.unitCode}, Enquiry: {self.enquiry}, Queue: {self.queue}>"

    @validates('studentName')
    def validates_studentName(self, key, studentName):
        for char in studentName:
            if char.isnumeric() or char in invalidChar:
                raise ValueError("Invalid character in studentName")

        return studentName

    @validates('studentNumber')
    def validate_studentNumber(self, key, studentNumber):
        if len(studentNumber) != 8:
            raise ValueError("studentNumber must be 8 digits")
        return int(studentNumber)

    @validates('unitCode')
    def validate_unitCode(self, key, unitCode):
        for i, c in enumerate(unitCode):
            if (i < 4 and not (c.isupper() or c.islower())) or (i >= 4 and not c.isnumeric()):
                raise ValueError("unitCode must be of the form CCCCNNNN")
        return unitCode

    @validates('enquiry')
    def validate_enquiry(self, key, enquiry):
        return enquiry

    @validates('queue')
    def validate_queue(self, key, queue):
        if queue not in queueType:
            raise ValueError('Queue is an invalid type')
        else:
            return queue

    @validates('status')
    def validate_status(self, key, status):
        if status not in statusType:
            raise ValueError('Status is an invalid type')
        else:
            return status

app/app/__init__.py
from flask import Flask
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

from config import Config


# Setup of Flask App
app = Flask(__name__)
app.config.from_object(Config)

# Setup of Database
db = SQLAlchemy(app)
migrate = Migrate(app, db)
db.create_all(app=app)

# Setup of Login Manager
login_manager = LoginManager()
login_manager.login_view = "auth.admin_login"
login_manager.init_app(app)

# Note: This import should be here (VERY VERY IMPORTANT)
# Otherwise, you will get "Circular Import Error"
# Because these imports below need some stuff in this file (eg. `app`)
from app.auth import auth
from app.routes import routes
from app.queue import queue
from app.export import export
from app.data import data

app.register_blueprint(routes, url_prefix="/")
app.register_blueprint(auth, url_prefix="/")
app.register_blueprint(queue, url_prefix="/")
app.register_blueprint(export, url_prefix="/")
app.register_blueprint(data, url_prefix="/")

app/app/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from app.models import User
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
from . import db
import os

auth = Blueprint('auth', __name__)

# To get admin username and password
basedir = os.path.abspath(os.path.dirname(__file__))
admin_username = os.environ.get('ADMIN_USERNAME')
admin_password = os.environ.get('ADMIN_PASSWORD')

def changed_admin_login():
    db.session.query(User).delete()
    db.session.commit()
    new_user = User(username=admin_username, role="Admin")
    new_user.set_password(admin_password)
    db.session.add(new_user)
    db.session.commit()

@auth.route('/login', methods=['GET', 'POST'])
def admin_login():
    admin = User.query.filter_by(username=admin_username).first()
    # If admin name/password changed delete previous admin user 
    if (admin and not admin.check_password(admin_password)) or not admin:
        changed_admin_login()
        
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        user = User.query.filter_by(username=username).first()
        if user:
            if user.check_password(password):
                flash("Logged in successfully! Hello " + user.username, category="success")
                login_user(user, remember=True)
                return redirect(url_for('routes.home'))
            else:
                flash("Incorrect username or password, please try again.", category="error")
        else:
            flash("Incorrect username or password, please try again.", category="error")

    return render_template('login.html', user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('routes.home'))

app/app/routes.py
from flask import Blueprint, render_template, request
from flask_login import login_required, current_user

from sqlalchemy.sql.elements import Null

from app.models import User

routes = Blueprint('routes', __name__)

# Main Routes
@routes.route('/')
@login_required
def home():
    # TODO: Implement user roles
    # Example:
    # if current_user.is_authenticated:
    #     user = User.query.filter_by(id = current_user.id).first()

    return render_template('home.html', user=current_user)

@routes.route('/data')
@login_required
def data():
    return render_template('data.html', user=current_user)

@routes.route('/export')
@login_required
def export():
    return render_template('export.html', user=current_user)

app/app/templates/analytics.html
{% extends "base.html" %}{% block title %}ReSQ{% endblock %}
{% block navbar_data %}active{% endblock %}
{% block header %} <a class="navbar-brand" href="javascript:;">Study Smarter Analytics</a>{%
endblock %} {% block content %}
<div class="row">
	<div class="col-md-2 ml-auto mr-auto">
		<div class="card">
			<div class="card-body">
				<label for="date"><small><i>Will display data from the week (from Sun-Sat) of chosen date</i></small></label><br>
				<label for="date"><b>Date:</b></label><br>
				<input type="date" name="date" id="date"/><br><br>
				<button id="dateSubmitForAnalytics" name="submit" class="btn btn-success">Submit</button>
			</div>
		</div>
	</div>
	<div class="col-md-10 ml-auto mr-auto">
		<div class="card card-chart">
			<div class="card-header card-header-info" data-header-animation="true">
				<div class="card-icon">
					<i class="material-icons">equalizer</i>
				  </div>
				  <h4 class="card-title">Weekly Data</h4>
			</div>
			<div class="card-body">
				<div id="studentsVisitedBarChart" class="ct-chart ct-double-octave"></div>
				<div class="card-actions">
					<div class="float-left" style="padding-left: 15%;">
						<button name="prev" type="button" class="btn btn-info btn-link" id="previousWeek">
							<i class="material-icons" style="font-size: 40px;">arrow_back</i>
						</button>
						<label for="prev">Previous Week</label>
					</div>
					<div class="float-right" style="padding-right: 15%;">
						<label for="prev">Next Week</label>
						<button name="next" type="button" class="btn btn-info btn-link" id="nextWeek">
							<i class="material-icons" style="font-size: 40px;">arrow_forward</i>
						</button>
					</div>
				</div>
				<h4 class="card-title">Students visited per day</h4>
			</div>
			<div class="card-footer"></div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-6 ml-auto mr-auto">
		<div class="card card-chart">
			<div class="card-header card-header-info">
				<div class="card-icon">
					<i class="material-icons">pie_chart</i>
				  </div>
				  <h4 class="card-title">Units for this week</h4>
			</div>
			<div class="card-body">
				<div id="unitsPieChart" class="ct-chart ct-double-octave" style="padding-bottom: 10%;"></div>
			</div>
			<div class="card-footer"></div>
		</div>
	</div>
	<div class="col-md-6 ml-auto mr-auto">
		<div class="card card-chart">
			<div class="card-header card-header-info">
				<div class="card-icon">
					<i class="material-icons">pie_chart</i>
				  </div>
				  <h4 class="card-title">Staff requested this week</h4>
			</div>
			<div class="card-body">
				<div id="unitsStaffChart" class="ct-chart ct-double-octave" style="padding-bottom: 10%;"></div>
			</div>
			<div class="card-footer"></div>
		</div>
	</div>
</div>
{% endblock %}

app/app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>ReSQ</title>
	<!-- Required meta tags -->
	<meta charset="utf-8" />
	<meta content="width=device-width, initial-scale=1.0" name="viewport" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<!--     Fonts and icons     -->
	<link rel="stylesheet" type="text/css"
		href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
	<link rel="stylesheet" href="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">
	<link rel="icon" href="{{ url_for('static', filename='img/favicon.ico') }}"> 
    <script src="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>
	<!-- Material Kit CSS -->
	<link href="{{ url_for('static', filename='css/material-dashboard.css') }}" rel="stylesheet" />
	<link href="{{ url_for('static', filename='custom/ourstyle.css') }}" rel="stylesheet" />
</head>

<body {% block body_attr %}{% endblock %}>
	<div class="wrapper">
		<div class="sidebar" data-color="azure" data-background-color="white" data-image="nothing">
			<!--
      Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"
      Tip 2: you can also add an image using data-image tag
    -->
			<div class="logo">
				<a href="{{ url_for('routes.home')}}" class="logo-normal resqLogo" style="margin-left: 20px">ReSQ</a>
			</div>
			{% block navbar %}<div class="sidebar-wrapper">
				<ul class="nav">
					<li class="{% block navbar_home %}{% endblock %}">
						<a class="nav-link" href="{{ url_for('routes.home')}}">
							<i class="material-icons">list</i>
							<p>Queue</p>
						</a>
					</li>
					<li class="{% block navbar_data %}{% endblock %}">
						<a class="nav-link" href="{{ url_for('routes.data')}}">
							<i class="material-icons">insights</i>
							<p>Data Analytics</p>
						</a>
					</li>
					<li class="{% block navbar_export %}{% endblock %}">
						<a class="nav-link" href="{{ url_for('routes.export')}}">
							<i class="material-icons">arrow_circle_down</i>
							<p>Export Data</p>
						</a>
					</li>
					<!-- more sidebar itens here -->
				</ul>
			</div>{% endblock %}
			<div class="sidebar-background"></div>
		</div>
		<div class="main-panel">
			<!-- Navbar -->
			<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top">
				<div class="container-fluid">
					<div class="navbar-wrapper">{% block header %} {% endblock %}</div>
					<button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index"
						aria-expanded="false" aria-label="Toggle navigation">
						<span class="sr-only">Toggle navigation</span>
						<span class="navbar-toggler-icon icon-bar"></span>
						<span class="navbar-toggler-icon icon-bar"></span>
						<span class="navbar-toggler-icon icon-bar"></span>
					</button>
					{% if user.is_authenticated %}
					<div class="collapse navbar-collapse justify-content-end">
						<ul class="navbar-nav">
							<li class="nav-item">
								<a class="nav-link" href="https://uwa-cits3200-18-2021.github.io/ReSQ/">
									<i class="material-icons">article</i> Documentation
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="{{ url_for('auth.logout')}}">
									<i class="material-icons">logout</i> Admin Log-out
								</a>
							</li>
							<!-- any other navbar items here -->
						</ul>
					</div>
					{% endif %}
				</div>
			</nav>
			
			<!-- End Navbar -->
			<div class="content">
				<div class="container-fluid">{% block content %}{% endblock %}</div>
			</div>
			<footer class="footer">
				<div class="container-fluid">
					<nav class="float-right">
						<ul>
							<li>
								<p>Realtime STUDYSmarter Queue</p>
							</li>
						</ul>
					</nav>
				</div>
			</footer>
		</div>
	</div>
	
	<!--   Core JS Files   -->
	<script href="{{ url_for('static', filename='js/core/jquery.min.js') }}" type="text/javascript"></script>
	<script href="{{ url_for('static', filename='js/core/popper.min.js') }}" type="text/javascript"></script>
	<script href="{{ url_for('static', filename='js/core/bootstrap-material-design.min.js') }}"
		type="text/javascript"></script>
	<script href="{{ url_for('static', filename='js/plugins/moment.min.js') }}" type="text/javascript"></script>
	<!-- Control Center for Material Kit: parallax effects, scripts for the example pages etc -->
	<script href="{{ url_for('static', filename='js/material-dashboard.js?v=2.2.2') }}" type="text/javascript"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
	<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
	<script src="{{ url_for('static', filename='custom/global.js') }}"></script>
	{% block scripts %}{% endblock %}
	
</body>

</html>

app/app/templates/data.html
{% extends "base.html" %}{% block title %}ReSQ{% endblock %}
{% block navbar_data %}active{% endblock %}
{% block header %} <a class="navbar-brand" href="javascript:;">Study Smarter Analytics</a>{%
endblock %} {% block content %}
<div class="row">
	<div class="col-md-2 ml-auto mr-auto">
		<div class="card">
			<div class="card-body">
				<label for="date"><small><i>Will display data from the week (from Sun-Sat) of chosen date</i></small></label><br>
				<label for="date"><b>Date:</b></label><br>
				<input type="date" name="date" id="date"/><br><br>
				<button id="dateSubmitForAnalytics" name="submit" class="btn btn-success">Submit</button>
			</div>
		</div>
	</div>
	<div class="col-md-10 ml-auto mr-auto">
		<div class="card card-chart">
			<div class="card-header card-header-info">
				<div class="card-icon">
					<i class="material-icons">equalizer</i>
				  </div>
				  <h4 class="card-title">Weekly Data</h4>
			</div>
			<div class="card-body">
				<div id="studentsVisitedBarChart" class="ct-chart ct-double-octave"></div>
				<h4 class="card-title">Students visited per day</h4>
			</div>
			<div class="card-footer"></div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-6 ml-auto mr-auto">
		<div class="card card-chart">
			<div class="card-header card-header-info">
				<div class="card-icon">
					<i class="material-icons">pie_chart</i>
				  </div>
				  <h4 class="card-title">Units for this week</h4>
			</div>
			<div class="card-body">
				<div id="unitsPieChart" class="ct-chart ct-double-octave" style="padding-bottom: 10%;"></div>
			</div>
			<div class="card-footer"></div>
		</div>
	</div>
	<div class="col-md-6 ml-auto mr-auto">
		<div class="card card-chart">
			<div class="card-header card-header-info">
				<div class="card-icon">
					<i class="material-icons">pie_chart</i>
				  </div>
				  <h4 class="card-title">Staff requested this week</h4>
			</div>
			<div class="card-body">
				<div id="unitsStaffChart" class="ct-chart ct-double-octave" style="padding-bottom: 10%;"></div>
			</div>
			<div class="card-footer"></div>
		</div>
	</div>
</div>
{% endblock %}
{% block scripts %}
<script src="{{ url_for('static', filename='custom/data.js') }}"></script>
{% endblock %}

app/app/templates/export.html
{% extends "base.html" %}
{% block navbar_export %}active{% endblock %}
{% block header %} <a class="navbar-brand" href="javascript:;">Export Data</a>{% endblock %}
{% block content %}
<div class="row">
	<div class="col-md-10 ml-auto mr-auto">
		<div class="card card-chart">
			<div class="card-header card-header-info">
				<h4 class="card-title">Export to CSV</h4>
			</div>
			<div class="card-body">
				<div class="export">
					<label><input type="radio" id="dateRange1" name="dateRangeSelector" value="Last Day" checked>&emsp;Last Day</label>
					<label><input type="radio" id="dateRange2" name="dateRangeSelector" value="Last Week">&emsp;Last Week</label>
					<label><input type="radio" id="dateRange3" name="dateRangeSelector" value="Last Month">&emsp;Last Month</label>
					<label><input type="radio" id="dateRange4" name="dateRangeSelector" value="Last Year">&emsp;Last Year</label>
					<label><input type="radio" id="dateRange5" name="dateRangeSelector" value="All Time">&emsp;All Time</label>
					<label><input type="radio" id="dateRange6" name="dateRangeSelector" value="Custom">&emsp;Custom</label>
					<div class="date_selector" style="display: none">
						<table>
							<tr>
								<td align="right">Start Date</td>
								<td align="left"><input type="date" name="startDate" id="startDate"></td>
							</tr>
							<tr>
								<td align="right">End Date</td>
								<td align="left"><input type="date" name="endDate" id="endDate"></td>
							</tr>
						</table>
					</div>
				</div>
				<button id="dateSubmit" class="btn btn-success">Submit</button>
			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block scripts %}
<script src="{{ url_for('static', filename='custom/export.js') }}"></script>
{% endblock %}

app/app/templates/home.html
{% extends "base.html" %}{% block title %}ReSQ{% endblock %}
{% block navbar_home %}active{% endblock %}
{% block header %}
<a class="navbar-brand" href="javascript:;">STUDYSmarter and Librarian Queues</a>{% endblock %} {% block
content %}
<div class="row">
	<div class="card col-md-10 currentSessions">
		<h4 class="card-header card-header-info">
			Current Sessions<span class="material-icons float-right"> group </span>
		</h4>
		<div class="card-body">
			<table class="table" id="inSession">
				<thead>
					<tr>
						<th>Team</th>
						<th>Name</th>
						<th>Student Number</th>
						<th>Unit Code</th>
						<th class="text-right">Enquiry Type</th>
						<th class="text-right">Session Time</th>
						<th class="text-right">End Session</th>
					</tr>
				</thead>
				<tbody id="inSessionDataTable"></tbody>
			</table>
		</div>
	</div>
	<div class="col-md-2">
		<div class="card-body">
			<button onclick="showAddToQueue()" type="button" class="btn btn-lg btn-round btn-queue">Add to Queue</button>
			<div class="addTeam card">
				<h4 class="card-header card-header-info">STUDYSmarter Team Available</h4>
				<div class="row card-body text-center">
					<span class="material-icons dec" id="studySmarterAvailableDecrement">remove_circle_outline</span>
					<div id="studySmarterAvailableCount">1</div>
					<span class="material-icons inc" id="studySmarterAvailableIncrement">add_circle_outline</span>
				</div>
			</div>
			<div class="addTeam card text-center">
				<h4 class="card-header card-header-info">Librarians Available</h4>
				<div class="row card-body text-center">
					<span class="material-icons dec" id="librariansAvailableDecrement">remove_circle_outline</span>
					<div id="librariansAvailableCount">1</div>
					<span class="material-icons inc" id="librariansAvailableIncrement">add_circle_outline</span>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row queues">
	<div class="card queue">
		<h4 class="card-header card-header-info" data-color="green">
			STUDYSmarter Queue<span class="material-icons float-right"> lightbulb </span>
		</h4>
		<div class="card-body">
			<table class="table" id="SSQueueTable">
				<thead>
					<tr>
						<th>Name</th>
						<th>Student No.</th>
						<th>Unit Code</th>
						<th class="text-right">Enquiry Type</th>
						<th class="text-right">Wait Time</th>
						<th class="text-right">Actions</th>
					</tr>
				</thead>
				<tbody id="studysmarterDataTable"></tbody>
			</table>
		</div>
	</div>
	<div class="card queue">
		<h4 class="card-header card-header-info">
			Librarian Queue<span class="material-icons float-right"> menu_book </span>
		</h4>
		<div class="card-body">
			<table class="table" id="libQueueTable">
				<thead>
					<tr>
						<th>Name</th>
						<th>Student No.</th>
						<th>Unit Code</th>
						<th class="text-right">Enquiry Type</th>
						<th class="text-right">Wait Time</th>
						<th class="td-actions text-right">Actions</th>
					</tr>
				</thead>
				<tbody id="librarianDataTable"></tbody>
			</table>
		</div>
	</div>
</div>
<div id="addToQueue">
	<div class="card col-md-3 addToQueue-content">
		<h3 class="card-header card-header-info">Add to Queue</h3>
		<div class="card-body">
			<span class="close" onclick="hideAddToQueueForm()">&times;</span>
			<form autocomplete="off" id="addToQueueForm">
				<label for="studentName"><b>Student Name</b></label>
				<input type="text" maxlength="50" id="studentName" class="form-control" required />
				<label for="studentNumber"><b>Student Number</b></label>
				<input type="text" minlength="8" maxlength="8" id="studentNumber" class="form-control" required />
				<label for="unitCode"><b>Unit Code</b></label>
				<input type="text" id="unitCode" minlength="8" maxlength="8" class="form-control" required />
				<div class="form-group-lg">
					<label><b>Team</b></label><br>
					<label><input type="radio" id="queue" name="queueSelector" value="STUDYSmarter" checked>&emsp;STUDYSmarter</label><br>
					<label><input type="radio" id="queue" name="queueSelector" value="Librarian">&emsp;Librarian</label><br>
				</div>
				<div class="form-group-lg">
					<label for="enquiry"><b>Enquiry Type</b></label>
					<input type="text" id="enquiry" list="enquiryEntries" class="form-control" required />
					<datalist id="enquiryEntries">
						<option>Essay</option>
						<option>Grammar</option>
						<option>Lab Report</option>
						<option>Assignment</option>
						<option>Literature Research</option>
						<option>Research Proposal</option>
						<option>Thesis/Paper</option>
						<option>IELTS</option>
						<option>Oral Presentation</option>
						<option>Referencing</option>
						<option>Finding Sources</option>
						<option>Endnote</option>
					</datalist>
				</div>
				<br />
				<input type="submit" value="ADD" class="btn btn-primary">
			</form>
		</div>
	</div>
</div>
{% endblock %}
{% block scripts %}
<script src="{{ url_for('static', filename='custom/queue.js') }}"></script>
{% endblock %}

app/app/templates/login.html
{% extends "base.html" %}{% block title %}ReSQ{% endblock %}
{% block header %}
<a class="navbar-brand" href="javascript:;">STUDYSmarter and Librarian Queue Log In</a>{% endblock %} 
{% block content %}
<div class="container">
	<div class="row">
	  <div class="col-lg-6 col-md-6 col-sm-8 ml-auto mr-auto">
		<form class="form" method="POST">
		  <div class="card card-login card-hidden">
			<div class="card-header card-header-info text-center">
			  <h4 class="card-title">Login</h4>
			</div>
			<div class="card-body">
			  <span class="bmd-form-group">
				<div class="input-group">
				  <div class="input-group-prepend">
					<span class="input-group-text">
					  <i class="material-icons">face</i>
					</span>
				  </div>
				  <input type="text" class="form-control" placeholder="Username..."type="text"
				  name="username"
				  id="username"
				  value="{{request.form.username}}"
				  required=""
				  autocomplete="off">
				</div>
			  </span>
			  <span class="bmd-form-group">
				<div class="input-group">
				  <div class="input-group-prepend">
					<span class="input-group-text">
					  <i class="material-icons">lock_outline</i>
					</span>
				  </div>
				  <input type="password" class="form-control" placeholder="Password..." name="password" id="password" value="{{request.form.password}}" required="">
				</div>
			  </span>
			</div>
			<div class="card-footer justify-content-center">
			  <input type="submit" class="btn btn-info btn-link btn-lg" name="" value="Login" />
			</div>
		  </div>		  
		  {% with messages = get_flashed_messages(category_filter=["error"]) %}
   				{% if messages %}
      				{% for message in messages %}
					  <div class="alert alert-danger">
						  <strong>{{message}}</strong>
					  </div>
					{% endfor %}
				{% endif %}
			{% endwith %}		
		</form>
	  </div>
	</div>
  </div>
</div>
{% endblock %}